---
# tasks file for vector-role
# - name: Get vector distrib
#   ansible.builtin.get_url:
#     url: '{{ vector_url }}'
#     dest: './{{ vector_package }}'
# - name: Install vector packages
#   become: true
#   ansible.builtin.yum:
#     disable_gpg_check: true
#     name:
#       - '{{ vector_package }}'

- name: Choose system family
  ansible.builtin.include_tasks: yum.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Choose system family
  ansible.builtin.include_tasks: apt.yml
  when: ansible_facts['os_family'] == "Debian"
