---
# tasks file for vector-role
- name: Get vector distrib
  ansible.builtin.get_url:
    url: '{{ vector_url }}'
    dest: './{{ vector_package }}'
- name: Install vector packages
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name:
      - '{{ vector_package }}'
