---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: false
    dockerfile: dockerfile_centos

  - name: instance_ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
