---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: 'Check if vector is installed'
      package_facts:
        manager: 'auto'

    - name: Vector test result
      assert:
        that: "'vector' in ansible_facts.packages"
